import { TextTemplate, TemplateCategory } from "../types";

export const BUILTIN_CANVAS_TEMPLATES: TextTemplate[] = [
  {
    id: "split-reveal",
    label: "Split Reveal Lower Third",
    category: "lower-third",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "bg-bar",
        shape: "rect",
        fill: "rgba(30, 30, 40, 0.85)",
        stroke: { color: "#7c6fff", width: 2 },
        x: 735, // Centered: (1920 - 450) / 2
        y: 500, // Centered vertically
        width: 450,
        height: 120,
        animation: {
          in: "slide-up",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "primary-name",
        content: "Alex Rivers",
        fontFamily: "Poppins",
        fontSize: 36,
        fontWeight: 700,
        color: "#ffffff",
        align: "center",
        x: 735,
        y: 495,
        width: 450,
        height: 50,
        role: "primary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "secondary-title",
        content: "Creative Director",
        fontFamily: "Poppins",
        fontSize: 24,
        fontWeight: 400,
        color: "#9A9AAA",
        align: "center",
        x: 735,
        y: 545,
        width: 450,
        height: 40,
        role: "secondary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.7,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "modern-opener",
    label: "Modern Title Opener",
    category: "title-card",
    duration: 4,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "block-bg",
        shape: "rect",
        fill: "#7c6fff",
        x: 460, // Centered: (1920 - 1000) / 2
        y: 400, // Centered vertically
        width: 1000,
        height: 280,
        animation: {
          in: "scale-in",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.4,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "title-text",
        content: "EXPLORE MORE",
        fontFamily: "Poppins",
        fontSize: 84,
        fontWeight: 700,
        color: "#ffffff",
        align: "center",
        x: 460,
        y: 440,
        width: 1000,
        height: 100,
        role: "primary",
        animation: {
          in: "slide-down",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "subtitle-text",
        content: "A Cinematic Experience",
        fontFamily: "Poppins",
        fontSize: 32,
        fontWeight: 400,
        color: "#a49bff",
        align: "center",
        x: 460,
        y: 560,
        width: 1000,
        height: 50,
        role: "secondary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.8,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "clean-caption",
    label: "Clean Caption Bar",
    category: "caption",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "caption-bg",
        shape: "rect",
        fill: "rgba(0, 0, 0, 0.7)",
        x: 460, // Centered: (1920 - 1000) / 2
        y: 490, // Centered vertically
        width: 1000,
        height: 100,
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.3,
          outDuration: 0.2,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "caption-content",
        content: "Enter your subtitles or captions here",
        fontFamily: "Arial",
        fontSize: 32,
        fontWeight: 600,
        color: "#ffd43b",
        align: "center",
        x: 460,
        y: 515,
        width: 1000,
        height: 50,
        role: "primary",
        animation: {
          in: "typewriter",
          out: "fade",
          inDuration: 1.0,
          outDuration: 0.2,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "pill-callout",
    label: "Clean Pill Callout",
    category: "callout",
    duration: 3,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "pill-bg",
        shape: "circle",
        fill: "#ffd43b",
        x: 800, // Centered: (1920 - 320) / 2
        y: 500, // Centered vertically
        width: 320,
        height: 80,
        animation: {
          in: "scale-in",
          out: "scale-out",
          inDuration: 0.4,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "callout-text",
        content: "LOOK HERE!",
        fontFamily: "Poppins",
        fontSize: 32,
        fontWeight: 700,
        color: "#000000",
        align: "center",
        x: 800,
        y: 515,
        width: 320,
        height: 50,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "social-subscribe",
    label: "Youtube Subscribe Pill",
    category: "social",
    duration: 4,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "btn-bg",
        shape: "rect",
        fill: "#ff0000",
        x: 810, // Centered: (1920 - 300) / 2
        y: 505, // Centered vertically
        width: 300,
        height: 70,
        animation: {
          in: "slide-up",
          out: "slide-down",
          inDuration: 0.4,
          outDuration: 0.3,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "sub-label",
        content: "SUBSCRIBE",
        fontFamily: "Poppins",
        fontSize: 28,
        fontWeight: 700,
        color: "#ffffff",
        align: "center",
        x: 810,
        y: 515,
        width: 300,
        height: 50,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.2,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "countdown-timer",
    label: "Futuristic Countdown",
    category: "countdown",
    duration: 5,
    canvasWidth: 1920,
    canvasHeight: 1080,
    layers: [
      {
        kind: "shape",
        id: "outer-ring",
        shape: "circle",
        fill: "rgba(124, 111, 255, 0.1)",
        stroke: { color: "#7c6fff", width: 4 },
        x: 810, // Centered: (1920 - 300) / 2
        y: 390, // Centered vertically
        width: 300,
        height: 300,
        animation: {
          in: "scale-in",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.4,
          hold: "full",
        },
      },
      {
        kind: "text",
        id: "timer-digits",
        content: "5",
        fontFamily: "Poppins",
        fontSize: 120,
        fontWeight: 700,
        color: "#ffffff",
        align: "center",
        x: 810,
        y: 440,
        width: 300,
        height: 200,
        role: "primary",
        animation: {
          in: "fade",
          out: "fade",
          inDuration: 0.3,
          outDuration: 0.3,
          hold: "full",
        },
      },
    ],
  },
  {
    id: "kinetic-split-title",
    label: "Kinetic Stagger Opener",
    category: "kinetic-type",
    duration: 4,
    canvasWidth: 1920,
    canvasHeight: 1080,
    variables: {
      title: {
        key: "title",
        label: "Title Text",
        type: "string",
        defaultValue: "FUTURE MOTION",
      },
      subtitle: {
        key: "subtitle",
        label: "Subtitle Text",
        type: "string",
        defaultValue: "ADVANCED TYPOGRAPHY STUDIO",
      },
    },
    layers: [
      {
        kind: "text",
        id: "main-title",
        content: "{{title}}",
        fontFamily: "Poppins",
        fontSize: 72,
        fontWeight: 900,
        color: "#ffffff",
        align: "center",
        x: 460,
        y: 440,
        width: 1000,
        height: 100,
        role: "primary",
        animation: {
          in: "scale-pop",
          out: "fade",
          inDuration: 0.8,
          outDuration: 0.4,
          hold: "full",
        },
        splitAnimator: {
          splitBy: "character",
          direction: "start-to-end",
          delayPerUnit: 0.03,
          overlap: 0.6,
          initialTransform: {
            y: 40,
            opacity: 0,
            scale: 0.7,
            rotateX: 45,
            blur: 8,
          },
          easing: "cubic-bezier",
          bezier: { x1: 0.2, y1: 0.8, x2: 0.2, y2: 1.0 },
        },
        anchor: {
          anchorPoint: "center",
          maxWidthPercentage: 90,
        },
      },
      {
        kind: "text",
        id: "sub-title",
        content: "{{subtitle}}",
        fontFamily: "Inter Variable",
        fontSize: 22,
        fontWeight: 600,
        color: "#7c6fff",
        letterSpacing: 6,
        align: "center",
        x: 460,
        y: 550,
        width: 1000,
        height: 40,
        role: "secondary",
        animation: {
          in: "track-in",
          out: "fade",
          inDuration: 0.9,
          outDuration: 0.4,
          hold: "full",
        },
        anchor: {
          anchorPoint: "center",
          maxWidthPercentage: 85,
        },
      },
    ],
  },
  {
    id: "responsive-speaker-lower-third",
    label: "Responsive Speaker Badge",
    category: "lower-third",
    duration: 5,
    canvasWidth: 1920,
    canvasHeight: 1080,
    variables: {
      speakerName: {
        key: "speakerName",
        label: "Speaker Name",
        type: "string",
        defaultValue: "Sarah Chen",
      },
      speakerRole: {
        key: "speakerRole",
        label: "Role / Organization",
        type: "string",
        defaultValue: "VP of Product @ Clypra",
      },
    },
    layers: [
      {
        kind: "text",
        id: "badge-name",
        content: "{{speakerName}}",
        fontFamily: "Poppins",
        fontSize: 32,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "#1E1E28",
        backgroundOpacity: 0.95,
        backgroundRadius: 8,
        backgroundBorderColor: "#7c6fff",
        backgroundBorderWidth: 2,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 20,
        paddingRight: 20,
        align: "left",
        x: 100,
        y: 860,
        width: "auto",
        height: "auto",
        overflow: "expand-panel",
        role: "primary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.5,
          outDuration: 0.3,
          hold: "full",
        },
        anchor: {
          anchorPoint: "bottom-left",
          offsetPercentageX: 5,
          offsetPercentageY: 10,
        },
      },
      {
        kind: "text",
        id: "badge-role",
        content: "{{speakerRole}}",
        fontFamily: "Inter Variable",
        fontSize: 18,
        fontWeight: 500,
        color: "#9A9AAA",
        backgroundColor: "#121218",
        backgroundOpacity: 0.85,
        backgroundRadius: 6,
        paddingTop: 8,
        paddingBottom: 8,
        paddingLeft: 16,
        paddingRight: 16,
        align: "left",
        x: 100,
        y: 930,
        width: "auto",
        height: "auto",
        overflow: "expand-panel",
        role: "secondary",
        animation: {
          in: "slide-right",
          out: "fade",
          inDuration: 0.6,
          outDuration: 0.3,
          hold: "full",
        },
        anchor: {
          anchorPoint: "bottom-left",
          offsetPercentageX: 5,
          offsetPercentageY: 4,
        },
      },
    ],
  },
];

export function getCanvasTemplatePreset(id: string): TextTemplate | undefined {
  return BUILTIN_CANVAS_TEMPLATES.find((t) => t.id === id);
}

export function getCanvasTemplatesByCategory(category: TemplateCategory): TextTemplate[] {
  return BUILTIN_CANVAS_TEMPLATES.filter((t) => t.category === category);
}
