import { TextEffectConfig, Preset } from "./types";
import {
  DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT,
  DEFAULT_FONT_SIZE,
} from "./engine/schema";

/** Style recipes (layer graphs): see `builtInRecipes` in src/engine/recipes.ts */

export const defaultConfig: TextEffectConfig = {
  text: "CLYPRA STUDIO",
  effectName: "My Effect",
  fontFamily: "Poppins",
  fontWeight: 700,
  fontStyle: "normal",
  fontSize: DEFAULT_FONT_SIZE,
  letterSpacing: 4,
  lineHeight: 1.2,
  fillType: "solid",
  fillColor: "#FFFFFF",
  fillGradientAngle: 90,
  fillGradientStops: [
    { color: "#FFFFFF", offset: 0 },
    { color: "#E0E0E0", offset: 100 },
  ],
  strokeEnabled: false,
  strokeColor: "#7C6FFF",
  strokeWidth: 4,
  strokePosition: "outside",
  strokeOpacity: 100,
  strokeLineJoin: "round",
  glowLayers: [
    { enabled: false, color: "#7C6FFF", blur: 20, opacity: 80, type: "outer" },
    { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
    { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" },
  ],
  shadowEnabled: false,
  shadowColor: "#000000",
  shadowBlur: 10,
  shadowOffsetX: 5,
  shadowOffsetY: 5,
  shadowOpacity: 80,
  shadowType: "drop",
  bevelEnabled: false,
  bevelDepth: 5,
  bevelHighlight: "#FFFFFF",
  bevelShadow: "#000000",
  bevelDirection: "bottom-right",
  bevelCoreColor: "#000000",
  bevelEdgeColor: "#2A2A38",
  bevelEdgeWidth: 0,
  bevelBlur: 0,
  bevelBlurColor: "#000000",
  bevelPerspectiveEnabled: false,
  bevelVanishingPointX: 40,
  bevelVanishingPointY: 80,
  bevelFocalLength: 400,
  stackEnabled: false,
  stackCount: 3,
  stackOffsetX: 10,
  stackOffsetY: -10,
  stackOpacityDecay: 20,
  stackColor1: "#FF7C00",
  stackColor2: "#00FFDD",
  stackColor3: "#FF00AA",
  stackColor4: "#AA00FF",
  panelEnabled: false,
  panelColor: "#1E1E26",
  panelOpacity: 80,
  panelRadius: 12,
  panelPaddingX: 40,
  panelPaddingY: 20,
  panelStrokeEnabled: false,
  panelStrokeColor: "#2A2A38",
  panelStrokeWidth: 2,
  canvasWidth: DEFAULT_CANVAS_WIDTH,
  canvasHeight: DEFAULT_CANVAS_HEIGHT,
  textPosX: "center",
  textPosY: "middle",
  wrapText: true,
  autoFitText: false,
};

/**
 * Return a fresh, explicit blank authoring state.
 *
 * A blank state is intentionally different from a loosely spread object:
 * every optional visual contributor is disabled while its parameters remain
 * present for the controls and the canonical scene migration. This prevents
 * object presence (panel/glow/shadow/etc.) from being interpreted as active.
 */
export function createBlankTextEffectConfig(): TextEffectConfig {
  return {
    ...defaultConfig,
    text: "MY TEXT",
    effectName: "Custom Effect",
    strokeEnabled: false,
    shadowEnabled: false,
    bevelEnabled: false,
    stackEnabled: false,
    panelEnabled: false,
    panelStrokeEnabled: false,
    perCharFillEnabled: false,
    glowLayers: defaultConfig.glowLayers.map((layer) => ({
      ...layer,
      enabled: false,
    })),
  };
}

export const builtInPresets: Preset[] = [
  {
    id: "classic-yellow",
    name: "Classic Yellow",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Classic Yellow",
      fontFamily: "Outfit Variable",
      fontWeight: 800,
      fontSize: 64,
      fillColor: "#FFE600",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 5,
      strokePosition: "outside",
      strokeOpacity: 100,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 3,
      shadowOpacity: 85,
    },
  },
  {
    id: "dark-pill",
    name: "Dark Pill",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Dark Pill",
      fontFamily: "Inter Variable",
      fontWeight: 700,
      fontSize: 56,
      fillColor: "#FFFFFF",
      panelEnabled: true,
      panelColor: "#000000",
      panelOpacity: 85,
      panelRadius: 28,
      panelPaddingX: 36,
      panelPaddingY: 12,
    },
  },
  {
    id: "outline-white",
    name: "Outline White",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Outline White",
      fontFamily: "Outfit Variable",
      fontWeight: 800,
      fontSize: 64,
      fillColor: "#FFFFFF",
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      strokePosition: "outside",
      strokeOpacity: 100,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowOpacity: 70,
    },
  },
  {
    id: "neon-pop",
    name: "Neon Pop",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Neon Pop",
      fontFamily: "Montserrat Variable",
      fontWeight: 800,
      fontSize: 64,
      fillColor: "#00F0FF",
      strokeEnabled: true,
      strokeColor: "#003344",
      strokeWidth: 2,
      strokePosition: "outside",
      glowLayers: [
        { enabled: true, color: "#00F0FF", blur: 15, opacity: 85, type: "outer" },
        { enabled: false, color: "#FF007C", blur: 40, opacity: 60, type: "outer" },
        { enabled: false, color: "#00F0FF", blur: 60, opacity: 40, type: "outer" },
      ],
      shadowEnabled: true,
      shadowColor: "rgba(0, 240, 255, 0.5)",
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowOpacity: 80,
    },
  },
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Minimal Clean",
      fontFamily: "Inter Variable",
      fontWeight: 600,
      fontSize: 58,
      fillColor: "#F5F5F7",
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowOpacity: 65,
    },
  },
  {
    id: "fire-orange",
    name: "Fire Orange",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Fire Orange",
      fontFamily: "Outfit Variable",
      fontWeight: 900,
      fontSize: 64,
      fillColor: "#FF5722",
      strokeEnabled: true,
      strokeColor: "#1A0500",
      strokeWidth: 4,
      strokePosition: "outside",
      strokeOpacity: 100,
      shadowEnabled: true,
      shadowColor: "rgba(255, 87, 34, 0.4)",
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowOpacity: 75,
    },
  },
  {
    id: "frosted-glass",
    name: "Frosted Glass",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Frosted Glass",
      fontFamily: "Inter Variable",
      fontWeight: 600,
      fontSize: 56,
      fillColor: "#FFFFFF",
      panelEnabled: true,
      panelColor: "#FFFFFF",
      panelOpacity: 18,
      panelRadius: 20,
      panelPaddingX: 32,
      panelPaddingY: 12,
      panelStrokeEnabled: true,
      panelStrokeColor: "rgba(255, 255, 255, 0.3)",
      panelStrokeWidth: 1.5,
      shadowEnabled: true,
      shadowColor: "rgba(0, 0, 0, 0.3)",
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      shadowOpacity: 50,
    },
  },
  {
    id: "typewriter-mono",
    name: "Typewriter Mono",
    category: "caption",
    config: {
      ...defaultConfig,
      text: "SAMPLE CAPTION",
      effectName: "Typewriter Mono",
      fontFamily: "Fira Code",
      fontWeight: 600,
      fontSize: 52,
      fillColor: "#FFFFFF",
      panelEnabled: true,
      panelColor: "#161622",
      panelOpacity: 90,
      panelRadius: 8,
      panelPaddingX: 24,
      panelPaddingY: 10,
      panelStrokeEnabled: true,
      panelStrokeColor: "#FFB800",
      panelStrokeWidth: 2,
    },
  },
];
